In [1]:
import sqlite3
import pandas as pd
from pathlib import Path

# SETUP FOLDER DAN CEK KONEKSI DATABASE

In [2]:
RAW_DIR = Path("../data/raw")
RAW_DIR.mkdir(parents=True, exist_ok=True)

db_path = RAW_DIR / "nfts.sqlite"

conn = sqlite3.connect(db_path)

# QUERY DATA

In [3]:
JUNE_1 = 1622505600
SEPT_1 = 1630454400

query = f"""
SELECT
    t.transaction_hash,
    t.block_number,
    t.timestamp,
    t.nft_address,
    t.token_id,
    t.from_address,
    t.to_address,
    t.transaction_value,
    m.timestamp AS mint_timestamp,
    sf.transfers_out AS transfers_out_from,
    sf.transfers_in AS transfers_in_from,
    st.transfers_out AS transfers_out_to,
    st.transfers_in AS transfers_in_to,
    ot.num_transitions
FROM transfers t
LEFT JOIN mints m
    ON t.token_id = m.token_id
    AND t.nft_address = m.nft_address
LEFT JOIN transfer_statistics_by_address sf
    ON t.from_address = sf.address
LEFT JOIN transfer_statistics_by_address st
    ON t.to_address = st.address
LEFT JOIN ownership_transitions ot
    ON t.from_address = ot.from_address
    AND t.to_address = ot.to_address
WHERE t.timestamp >= {JUNE_1}
  AND t.timestamp < {SEPT_1}
"""

# DATAFRAME

In [4]:
df = pd.read_sql_query(query, conn)

conn.close()

print(df.shape)

df.head()

(2539120, 14)

,transaction_hash,block_number,timestamp,nft_address,token_id,from_address,to_address,transaction_value,mint_timestamp,transfers_out_from,transfers_in_from,transfers_out_to,transfers_in_to,num_transitions
0,0x0c73daad5e6946e6b2f1374846d6ba3025d6e6a2569f...,12936373,1627776481,0x629A673A8242c2AC4B7B8C5D8735fbeac21A6205,6682934142305278177002530107138320246486863356...,0x25f1d709b329C7349b8209851E90eFa3a7f60178,0xC69b4c6fFDBaF843A0d0588c99E3C67f27069BEa,0.0,NaN,66,54,1,74608,10
1,0x0c73daad5e6946e6b2f1374846d6ba3025d6e6a2569f...,12936373,1627776481,0x629A673A8242c2AC4B7B8C5D8735fbeac21A6205,1198507443711741845273832738859307575893198744...,0x0737E7162C88E9FBB963334e4Bfe6e97447fF811,0xC69b4c6fFDBaF843A0d0588c99E3C67f27069BEa,0.0,1.622185e+09,31,35,1,74608,6
2,0x0c73daad5e6946e6b2f1374846d6ba3025d6e6a2569f...,12936373,1627776481,0x629A673A8242c2AC4B7B8C5D8735fbeac21A6205,1541220344281436903042142177888467401468454835...,0xA0fEc186c4b3FAd39ca373dFdd52E79C2495F2c3,0xC69b4c6fFDBaF843A0d0588c99E3C67f27069BEa,0.0,1.620922e+09,36,50,1,74608,19
3,0x0c73daad5e6946e6b2f1374846d6ba3025d6e6a2569f...,12936373,1627776481,0x629A673A8242c2AC4B7B8C5D8735fbeac21A6205,7993840355029527745913866651030234226423689128...,0x90bE22069560A9bAd99543B4A922d1FE34Ae84E9,0xC69b4c6fFDBaF843A0d0588c99E3C67f27069BEa,0.0,1.625500e+09,13,13,1,74608,4
4,0x0c73daad5e6946e6b2f1374846d6ba3025d6e6a2569f...,12936373,1627776481,0x629A673A8242c2AC4B7B8C5D8735fbeac21A6205,1123719749142984581497870712442861055686734521...,0xA8E9C42Ebb915EeEC5080B7Bcc5D844475595091,0xC69b4c6fFDBaF843A0d0588c99E3C67f27069BEa,0.0,1.618140e+09,21,12,1,74608,10

# OUTPUT CSV

In [5]:
output_path = RAW_DIR / "nft_transfers_jun_aug.csv"

df.to_csv(output_path, index=False)

print("Saved to:", output_path)

Saved to: ..\data\raw\nft_transfers_jun_aug.csv

# LOAD DATASET

In [6]:
df = pd.read_csv("../data/raw/nft_transfers_jun_aug.csv")

print(df.shape)
df.head()

(2539120, 14)

,transaction_hash,block_number,timestamp,nft_address,token_id,from_address,to_address,transaction_value,mint_timestamp,transfers_out_from,transfers_in_from,transfers_out_to,transfers_in_to,num_transitions
0,0x0c73daad5e6946e6b2f1374846d6ba3025d6e6a2569f...,12936373,1627776481,0x629A673A8242c2AC4B7B8C5D8735fbeac21A6205,6682934142305278177002530107138320246486863356...,0x25f1d709b329C7349b8209851E90eFa3a7f60178,0xC69b4c6fFDBaF843A0d0588c99E3C67f27069BEa,0.0,NaN,66,54,1,74608,10
1,0x0c73daad5e6946e6b2f1374846d6ba3025d6e6a2569f...,12936373,1627776481,0x629A673A8242c2AC4B7B8C5D8735fbeac21A6205,1198507443711741845273832738859307575893198744...,0x0737E7162C88E9FBB963334e4Bfe6e97447fF811,0xC69b4c6fFDBaF843A0d0588c99E3C67f27069BEa,0.0,1.622185e+09,31,35,1,74608,6
2,0x0c73daad5e6946e6b2f1374846d6ba3025d6e6a2569f...,12936373,1627776481,0x629A673A8242c2AC4B7B8C5D8735fbeac21A6205,1541220344281436903042142177888467401468454835...,0xA0fEc186c4b3FAd39ca373dFdd52E79C2495F2c3,0xC69b4c6fFDBaF843A0d0588c99E3C67f27069BEa,0.0,1.620922e+09,36,50,1,74608,19
3,0x0c73daad5e6946e6b2f1374846d6ba3025d6e6a2569f...,12936373,1627776481,0x629A673A8242c2AC4B7B8C5D8735fbeac21A6205,7993840355029527745913866651030234226423689128...,0x90bE22069560A9bAd99543B4A922d1FE34Ae84E9,0xC69b4c6fFDBaF843A0d0588c99E3C67f27069BEa,0.0,1.625500e+09,13,13,1,74608,4
4,0x0c73daad5e6946e6b2f1374846d6ba3025d6e6a2569f...,12936373,1627776481,0x629A673A8242c2AC4B7B8C5D8735fbeac21A6205,1123719749142984581497870712442861055686734521...,0xA8E9C42Ebb915EeEC5080B7Bcc5D844475595091,0xC69b4c6fFDBaF843A0d0588c99E3C67f27069BEa,0.0,1.618140e+09,21,12,1,74608,10

# MISSING VALUE

In [7]:
df.isnull().sum().sort_values(ascending=False)

mint_timestamp        333913
transaction_hash           0
timestamp                  0
nft_address                0
token_id                   0
block_number               0
from_address               0
to_address                 0
transaction_value          0
transfers_out_from         0
transfers_in_from          0
transfers_out_to           0
transfers_in_to            0
num_transitions            0
dtype: int64

# KONVERSI TIMESTAMP

In [8]:
df["timestamp_dt"] = pd.to_datetime(
    df["timestamp"],
    unit="s"
)

df["mint_timestamp_dt"] = pd.to_datetime(
    df["mint_timestamp"],
    unit="s",
    errors="coerce"
)

In [9]:
df["transaction_value"] = pd.to_numeric(
    df["transaction_value"],
    errors="coerce"
)

df["transaction_value"] = df["transaction_value"].fillna(0)

In [10]:
df = df[df["transaction_value"] > 0].copy()

print(df.shape)

(1582618, 16)

# REMOVE BURN ADDRESS

In [11]:
burn_addresses = [
    "0x0000000000000000000000000000000000000000",
    "0x000000000000000000000000000000000000dead"
]

df = df[
    (~df["from_address"].isin(burn_addresses)) &
    (~df["to_address"].isin(burn_addresses))
].copy()

print(df.shape)

(1563989, 16)

# DROP DUPLICATE

In [12]:
df = df.drop_duplicates(
    subset=["transaction_hash"]
)

print(df.shape)

(1491465, 16)

# SORT TEMPORAL

In [13]:
df = df.sort_values(
    by="timestamp"
).reset_index(drop=True)

# DISTRIBUSI BULAN

In [14]:
df["month"] = df["timestamp_dt"].dt.month

df["month"].value_counts().sort_index()

month
6     137143
7     276922
8    1077400
Name: count, dtype: int64

In [15]:
output_path = "../data/processed/nft_clean.csv"

df.to_csv(output_path, index=False)

print("Saved:", output_path)

Saved: ../data/processed/nft_clean.csv

In [ ]:
Dataset penelitian diambil dari transaksi NFT blockchain Ethereum periode Juni–Agustus 2021 menggunakan database SQLite. Data transaksi diperoleh dari tabel transfers dan diperkaya menggunakan beberapa tabel pendukung seperti mints, transfer_statistics_by_address, dan ownership_transitions.

Tahap preprocessing dilakukan untuk memastikan data siap digunakan pada proses labeling dan graph modeling. Beberapa proses preprocessing yang dilakukan meliputi:

1. Konversi Unix timestamp menjadi format datetime.
2. Konversi transaction_value menjadi numerik.
3. Filtering transaksi berbayar (transaction_value > 0).
4. Penghapusan burn address dan null address.
5. Penghapusan duplicate transaction berdasarkan transaction_hash.
6. Pengurutan data berdasarkan timestamp untuk menjaga urutan temporal transaksi.

Hasil preprocessing menghasilkan dataset bersih sebanyak:

Dataset	                Jumlah Data
Clean NFT Transactions	1.491.465 transaksi

Dataset kemudian digunakan pada tahap rule-based labeling.