In [1]:
import pandas as pd

plain_df = pd.read_csv("../outputs/metrics/graph_plain_final.csv")
class_weight_df = pd.read_csv("../outputs/metrics/graph_class_weight_final.csv")
focal_df = pd.read_csv("../outputs/metrics/graph_focal_loss_final.csv")

plain_df["model"] = "Plain"
class_weight_df["model"] = "Class Weight"
focal_df["model"] = "Focal Loss"

plain_df["threshold"] = 0.5
class_weight_df["threshold"] = 0.5
focal_df["threshold"] = 0.5

comparison_df = pd.concat(
    [plain_df, class_weight_df, focal_df],
    ignore_index=True
)

columns_order = [
    "model", "threshold",
    "accuracy", "precision", "recall", "f1",
    "roc_auc", "pr_auc",
    "tn", "fp", "fn", "tp"
]

existing_columns = [col for col in columns_order if col in comparison_df.columns]
comparison_df = comparison_df[existing_columns]

comparison_df

,model,threshold,accuracy,precision,recall,f1,roc_auc,pr_auc,tn,fp,fn,tp
0,Plain,0.5,0.999695,0.034483,0.015625,0.021505,0.716671,0.002937,298068,28,63,1
1,Class Weight,0.5,0.965294,0.001358,0.218750,0.002699,0.779439,0.068933,287798,10298,50,14
2,Focal Loss,0.5,0.999698,0.117647,0.062500,0.081633,0.738152,0.063517,298066,30,60,4

In [2]:
comparison_df.sort_values(
    by="recall",
    ascending=False
)

,model,threshold,accuracy,precision,recall,f1,roc_auc,pr_auc,tn,fp,fn,tp
1,Class Weight,0.5,0.965294,0.001358,0.218750,0.002699,0.779439,0.068933,287798,10298,50,14
2,Focal Loss,0.5,0.999698,0.117647,0.062500,0.081633,0.738152,0.063517,298066,30,60,4
0,Plain,0.5,0.999695,0.034483,0.015625,0.021505,0.716671,0.002937,298068,28,63,1

In [3]:
comparison_df.sort_values(
    by="accuracy",
    ascending=False
)

,model,threshold,accuracy,precision,recall,f1,roc_auc,pr_auc,tn,fp,fn,tp
2,Focal Loss,0.5,0.999698,0.117647,0.062500,0.081633,0.738152,0.063517,298066,30,60,4
0,Plain,0.5,0.999695,0.034483,0.015625,0.021505,0.716671,0.002937,298068,28,63,1
1,Class Weight,0.5,0.965294,0.001358,0.218750,0.002699,0.779439,0.068933,287798,10298,50,14

In [4]:
comparison_df.sort_values(
    by="f1",
    ascending=False
)

,model,threshold,accuracy,precision,recall,f1,roc_auc,pr_auc,tn,fp,fn,tp
2,Focal Loss,0.5,0.999698,0.117647,0.062500,0.081633,0.738152,0.063517,298066,30,60,4
0,Plain,0.5,0.999695,0.034483,0.015625,0.021505,0.716671,0.002937,298068,28,63,1
1,Class Weight,0.5,0.965294,0.001358,0.218750,0.002699,0.779439,0.068933,287798,10298,50,14

In [5]:
comparison_df.sort_values(
    by="precision",
    ascending=False
)

,model,threshold,accuracy,precision,recall,f1,roc_auc,pr_auc,tn,fp,fn,tp
2,Focal Loss,0.5,0.999698,0.117647,0.062500,0.081633,0.738152,0.063517,298066,30,60,4
0,Plain,0.5,0.999695,0.034483,0.015625,0.021505,0.716671,0.002937,298068,28,63,1
1,Class Weight,0.5,0.965294,0.001358,0.218750,0.002699,0.779439,0.068933,287798,10298,50,14

In [6]:
comparison_df.sort_values(
    by="roc_auc",
    ascending=False
)

,model,threshold,accuracy,precision,recall,f1,roc_auc,pr_auc,tn,fp,fn,tp
1,Class Weight,0.5,0.965294,0.001358,0.218750,0.002699,0.779439,0.068933,287798,10298,50,14
2,Focal Loss,0.5,0.999698,0.117647,0.062500,0.081633,0.738152,0.063517,298066,30,60,4
0,Plain,0.5,0.999695,0.034483,0.015625,0.021505,0.716671,0.002937,298068,28,63,1

In [7]:
comparison_df.sort_values(
    by="fp",
    ascending=True
)

,model,threshold,accuracy,precision,recall,f1,roc_auc,pr_auc,tn,fp,fn,tp
0,Plain,0.5,0.999695,0.034483,0.015625,0.021505,0.716671,0.002937,298068,28,63,1
2,Focal Loss,0.5,0.999698,0.117647,0.062500,0.081633,0.738152,0.063517,298066,30,60,4
1,Class Weight,0.5,0.965294,0.001358,0.218750,0.002699,0.779439,0.068933,287798,10298,50,14